FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12.18-sid-run

WORKDIR /usr/src/app

COPY package*.json ./

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*

COPY . ./

CMD ["npm", "start"]